## Part 02 데이터 핸들링 - 3장 데이터 변환
### 1절: 파생변수 생성

- **파생변수** : 사용자가 특정 의미를 부여하여 만든 변수. 다양한 함수와 조건문을 활용하여 생성

<br>

#### 컬럼 추가
- df에서 컬럼을 추가하는 방법
- ```df['컬럼명'] = 추가할_컬럼의_객체```

In [2]:
# 사이킷런의 dataset 모율 내 iris 데이터 호출
from sklearn.datasets import load_iris

In [5]:
# iris는 딕셔너리형과 유사한 구조로 key와 value를 가지고 있음
# 'data' : 2d array로 꽃 받침과 꽃잎의 길이, 넓이 (cm)
# 'target' : 1d array로 품종(숫자변환)
# 'target_names' : 1d array로 품종(문자)
# 'feature_names' : 2d array로 'data'의 컬럼명
iris = load_iris()
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [6]:
import pandas as pd

In [7]:
data = pd.DataFrame(iris.data, columns = iris.feature_names)
data

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [8]:
# 데이터 구조 확인
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
dtypes: float64(4)
memory usage: 4.8 KB


In [14]:
# 'ID' 컬럼을 새로 생성
# 1) [대괄호]를 이용한 방법 -> 마지막 열에 추가됨 -> 원하는 위치에 칼럼 추가하려면 insert() 메소드 사용
data['ID'] = range(150)
data.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   ID  
0   0  
1   1  
2   2  
3   3  
4   4

- ```df.insert(loc, column, value, ...)```

<br>

#### 인자
- **loc** : 추가를 원하는 열 위치 인덱스 번호
- **column** : 추가하고 싶은 열의 컬럼명
- **value** : 추가하고 싶은 열의 값

In [16]:
data = pd.DataFrame(iris.data, columns = iris.feature_names)

In [17]:
# 2) insert()를 이용한 방법
data.insert(0, column='ID', value=range(150))
data.head()

ID  sepal length (cm)  sepal width (cm)  petal length (cm)  \
0   0                5.1               3.5                1.4   
1   1                4.9               3.0                1.4   
2   2                4.7               3.2                1.3   
3   3                4.6               3.1                1.5   
4   4                5.0               3.6                1.4   

   petal width (cm)  
0               0.2  
1               0.2  
2               0.2  
3               0.2  
4               0.2

#### 컬럼 삭제
- ```drop()``` 메소드를 사용해 열을 삭제할 수 있음
- ```df.drop(labels, axis=0, inplace=False, ...)```

<br>

#### 인자
- **labels** : 삭제하고자 하는 행 또는 열 이름(리스트 가능)
- **axis** : 0은 행(row; default), 1은 열(column)
- **inplace** : 기존 df에 drop한 df를 저장할지에 대한 여부. False(default)는 drop한 df를 새로운 변수에 다시 할당해야 하고, True는 별도 할당 없이 기존의 df의 변경

In [20]:
data_dp = data.drop('ID', axis=1)
data_dp.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

#### 구간화 (비닝; binning)
- 특정 칼럼에 대해 수치형(연속형) 값들을 이산형/범주형으로 변환하는 것
- Pandas의 ```cut()``` 함수와 ```qcut()``` 함수로 수행 가능
- ```cut()```은 값을 기반으로 하고, ```qcut()```은 분위수 기반으로 함

<br>

#### cut() 함수 사용법
- ```pandas.cut(x, bins, labels=None, right=True, ...)```

<br>

#### 인자
- **x** : 구간화할 1d 형태의 모든 배열(1차원 배열, 시리즈, 리스트)
- **bins** : 정수, 숫자열 등
   - 정수 입력시 정수 개의 구간으로 분할됨
   - 숫자열 입력시 숫자열을 통해 구간 범위를 지정해 분할됨
- **labels** : 반환되는 구간의 레이블 지정 (default는 None으로 구간 범위를 반환)
- **right** : 우측 부등호의 등호 포함 여부 (e.g. right=True(default)는 구간 (1, 2]이 됨)

In [22]:
# cut
# [sepal length (cm)] 칼럼을 5개의 구간으로 분할
pd.cut(data['sepal length (cm)'], bins=5)

0       (5.02, 5.74]
1      (4.296, 5.02]
2      (4.296, 5.02]
3      (4.296, 5.02]
4      (4.296, 5.02]
           ...      
145     (6.46, 7.18]
146     (5.74, 6.46]
147     (6.46, 7.18]
148     (5.74, 6.46]
149     (5.74, 6.46]
Name: sepal length (cm), Length: 150, dtype: category
Categories (5, interval[float64, right]): [(4.296, 5.02] < (5.02, 5.74] < (5.74, 6.46] < (6.46, 7.18] < (7.18, 7.9]]

In [27]:
# 구간 (4, 5], (5, 6], (6, 7], (7, 8]로 분할
pd.cut(data['sepal length (cm)'], bins=[4, 5, 6, 7, 8], labels=['4-5', '5-6', '6-7', '7-8'])

0      5-6
1      4-5
2      4-5
3      4-5
4      4-5
      ... 
145    6-7
146    6-7
147    6-7
148    6-7
149    5-6
Name: sepal length (cm), Length: 150, dtype: category
Categories (4, object): ['4-5' < '5-6' < '6-7' < '7-8']

#### qcut() 함수 사용법
- ```pandas.qcut(x, q, labels=None, ...)```

<br>

#### 인자
- **x** : 구간화할 1d 배열이나 시리즈
- **q** : q-분위수 (e.g. 4는 4-분위수를 기준하여 동일한 수의 데이터로 분할)
- **labels** : 반환되는 구간의 레이블 지정 (default는 None으로 구간 범위를 반환)

In [31]:
# qcut
pd.qcut(data['sepal length (cm)'], q = 4)  # 4분위수마다 분할

0      (4.2989999999999995, 5.1]
1      (4.2989999999999995, 5.1]
2      (4.2989999999999995, 5.1]
3      (4.2989999999999995, 5.1]
4      (4.2989999999999995, 5.1]
                 ...            
145                   (6.4, 7.9]
146                   (5.8, 6.4]
147                   (6.4, 7.9]
148                   (5.8, 6.4]
149                   (5.8, 6.4]
Name: sepal length (cm), Length: 150, dtype: category
Categories (4, interval[float64, right]): [(4.2989999999999995, 5.1] < (5.1, 5.8] < (5.8, 6.4] < (6.4, 7.9]]

In [32]:
# 4분위수 확인
data['sepal length (cm)'].quantile([.25, .5, .75])

0.25    5.1
0.50    5.8
0.75    6.4
Name: sepal length (cm), dtype: float64

In [33]:
pd.qcut(data['sepal length (cm)'], q=10)   # 10분위수마다 분할

0                    (5.0, 5.27]
1                     (4.8, 5.0]
2      (4.2989999999999995, 4.8]
3      (4.2989999999999995, 4.8]
4                     (4.8, 5.0]
                 ...            
145                  (6.52, 6.9]
146                   (6.1, 6.3]
147                  (6.3, 6.52]
148                   (6.1, 6.3]
149                   (5.8, 6.1]
Name: sepal length (cm), Length: 150, dtype: category
Categories (10, interval[float64, right]): [(4.2989999999999995, 4.8] < (4.8, 5.0] < (5.0, 5.27] < (5.27, 5.6] ... (6.1, 6.3] < (6.3, 6.52] < (6.52, 6.9] < (6.9, 7.9]]

In [34]:
# 10분위수 확인 (0과 1은 최솟값, 최댓값)
data['sepal length (cm)'].quantile([0, .1, .2, .3, .4, .5, .6, .7, .8, .9, 1])

0.0    4.30
0.1    4.80
0.2    5.00
0.3    5.27
0.4    5.60
0.5    5.80
0.6    6.10
0.7    6.30
0.8    6.52
0.9    6.90
1.0    7.90
Name: sepal length (cm), dtype: float64

### 2절: 데이터 인코딩
- 사이킷런의 ML 알고리즘은 입력 데이터에 문자열을 허용하지 않아 문자열을 숫자형으로 바꾸는 과정이 필요함

<br>

#### 라벨 인코딩 (Label Encoding)
- 단순하게 문자열 값을 숫자형 카테고리 값으로 일대일 변환
- 가급적 트리 계열과 같은 특정 ML 알고리즘에서만 사용해야 하는데, 변환된 숫자가 대소의 의미를 가지게 되어 큰 숫자로 변환된 카테고리를 더 중요하게 생각할 수 있기 때문
- 파이썬에서 라벨 인코딩을 수행하는 가장 빠른 방법은 사이킷런의 preprocessing 모듈의 ```LabelEncoder``` 클래스를 사용하는 방법
- 클래스를 호출한 후 라벨 인코더 객체를 생성하여 ```fit()```과 ```transform()```을 통해 인코딩이 가능함

In [35]:
# 사이킷런 내의 preprocessing 모듈의 LabelEncoder 클래스 호출
from sklearn.preprocessing import LabelEncoder

In [37]:
obj = {'Class' : ['A', 'B', 'C', 'E', 'D', 'D', 'A', 'F']}
df = pd.DataFrame(obj)
df

Class
0     A
1     B
2     C
3     E
4     D
5     D
6     A
7     F

In [38]:
# 라벨 인코딩
encoder = LabelEncoder()               # 라벨 인코더 객체 생성
encoder.fit(df.Class)                  # 적합
labels = encoder.transform(df.Class)   # 변환
labels

array([0, 1, 2, 4, 3, 3, 0, 5])

In [40]:
# 숫자 값에 대응되는 원본 레이블
encoder.classes_

array(['A', 'B', 'C', 'D', 'E', 'F'], dtype=object)

- 다시 원본 문자열로 되돌리는 방법(디코딩)은 라벨 인코더 객체 내의 ```inverse_transform()```을 통해 가능하며 인자로 transform()의 반환 결과를 사용하면 됨

In [41]:
encoder.inverse_transform(labels)

array(['A', 'B', 'C', 'E', 'D', 'D', 'A', 'F'], dtype=object)

- 라벨 인코딩만을 위한 방법은 아니지만 numpy의 ```select()``` 함수와 pandas 시리즈객체의 메소드인 ```.map```을 이용해도 라벨 인코딩 수행 가능
- ```select()``` 함수는 특정 조건 목록(condlist)에 따라 선택 목록(choicelist)의 요소를 반환하는 함수임
- ```numpy.select(condlist, choicelist, ...)```

<br>

#### 인자
- **condlist** : 특정 조건 목록
- **choicelist** : 선택 목록

In [46]:
import numpy as np

In [43]:
# numpy.select()로 라벨 인코딩과 동일한 결과 만들기
# 조건 목록 생성
conditionlist = [ (df['Class'] == "A"),
                  (df['Class'] == "B"),
                  (df['Class'] == "C"),
                  (df['Class'] == "D"),
                  (df['Class'] == "E"),
                  (df['Class'] == "F") ]

In [44]:
# 조건과 매칭할 선택 목록 생성
choicelist = list(range(6))

In [47]:
np.select(condlist=conditionlist, choicelist=choicelist)

array([0, 1, 2, 4, 3, 3, 0, 5])

- ```.map()```은 입력된 매핑(mapping)이나 함수에 따라 시리즈의 맵 값(map value)를 반환 (즉, 시리즈를 대상으로 원하는 함수를 적용)하는 메소드
- ```시리즈.map(arg, ...)```

<br>

#### 인자
- **arg**: 적용하고자 하는 함수로, 딕셔너리 형을 통해 라벨 인코딩/디코딩이 가능. 시리즈 형태로 반환

In [48]:
# 시리즈.map으로 라벨 인코딩과 동일한 결과 만들기
df['Class'].map(arg = {'A':0, 'B':1, 'C':2, 'D':3, 'E':4, 'F':5})

0    0
1    1
2    2
3    4
4    3
5    3
6    0
7    5
Name: Class, dtype: int64

#### 원-핫 인코딩 (One-Hot Encoding)
- 라벨 인코딩에서의 문제점을 해결하기 위한 인코딩 방식
- 행 형태로 되어있는 값들을 열 형태로 차원을 변환한 뒤, 각 값에 해당하는 컬럼에만 1을 표시하고 나머지 컬럼에는 0을 표시하는 방법
- 파이썬에서 원-핫 인코딩은 OneHotEncoder 클래스를 사용해 변환 가능
- 데이터가 시리즈/리스트 등 1차원일 경우, OneHotEncoder 클래스 사용 전에 LabelEncoder 클래스나 .values 메소드 등으로 먼저 1차원 넘파이 배열로 변환한 후 2차원으로 한 번 더 변환할 필요가 있기 때문에 사이킷런에서 원-핫 인코딩을 통해 변환하는 방법은 번거로운 점도 있음

In [49]:
# 사이킷런 내의 preprocessing 모듈의 LabelEncoder, OneHotEncoder 클래스 호출
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [85]:
obj = {'Class' : ['A', 'B', 'C', 'E', 'D', 'D', 'A', 'F']}
df = pd.DataFrame(obj)
df

Class
0     A
1     B
2     C
3     E
4     D
5     D
6     A
7     F

In [86]:
# 라벨 인코딩 먼저 수행
encoder = LabelEncoder()
encoder.fit(df['Class'])

LabelEncoder()

In [87]:
# 2차원 레이블 변환
labels = encoder.transform(df['Class']).reshape(-1, 1)
labels

array([[0],
       [1],
       [2],
       [4],
       [3],
       [3],
       [0],
       [5]])

In [88]:
# 원-핫 인코딩
# sparse = False 옵션은 결과를 보통의 array 형태로 반환하기 위함
oh_encoder = OneHotEncoder(sparse_output=False)                      # sparse -> sparse_output
oh_encoder

OneHotEncoder(sparse_output=False)

In [90]:
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)

In [56]:
# 결과
oh_labels

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1.]])

- 원-핫 인코딩을 더미변수(Dummy Variable)라고도 하는데 더미변수란 주로 통계학의 회귀분석에서 사용되며 범주형 변수를 0 또는 1의 값으로 어떤 특징에 해당하는지의 여부를 표현하는 변수를 말함
- 판다스에서 이러한 더미변수를 생성하는 ```pandas.get_dummies()``` 함수를 제공함
- ```pandas.get_dummies(data, columns=None, drop_first=False, ...)```

<br>

#### 인자
- **data** : 입력할 데이터
- **columns** : 인코딩할 데이터프레임의 컬럼. default는 None으로 모든 열이 반환됨
- **drop_first** : 첫번째 고유 특징을 제거해 k-1개의 변수를 생성할지에 대한 여부. default는 False로 제거하지 않고 k개의 변수 생성

In [58]:
# pandas get_dummies() 함수를 사용
pd.get_dummies(df)

Class_A  Class_B  Class_C  Class_D  Class_E  Class_F
0     True    False    False    False    False    False
1    False     True    False    False    False    False
2    False    False     True    False    False    False
3    False    False    False    False     True    False
4    False    False    False     True    False    False
5    False    False    False     True    False    False
6     True    False    False    False    False    False
7    False    False    False    False    False     True

In [59]:
# 첫 번째 고유 특징을 제거해 k-1개의 변수 생성
pd.get_dummies(df, drop_first = True)

Class_B  Class_C  Class_D  Class_E  Class_F
0    False    False    False    False    False
1     True    False    False    False    False
2    False     True    False    False    False
3    False    False    False     True    False
4    False    False     True    False    False
5    False    False     True    False    False
6    False    False    False    False    False
7    False    False    False    False     True

- 원-핫 인코딩 구현 방법들
   1. 넘파이의 where 함수
   2. loc 인덱서와 부울 인덱싱 활용
      - 부울 인덱싱(Boolean Indexing)이란, 특정 조건 등의 해당 여부(True/False) 기반으로 해당 위치의 데이터를 인덱싱하는 것

In [61]:
# numpy.where()
df['Class_B'] = np.where(df['Class'] == 'B', 1, 0)
df['Class_C'] = np.where(df['Class'] == 'C', 1, 0)
df['Class_D'] = np.where(df['Class'] == 'D', 1, 0)
df['Class_E'] = np.where(df['Class'] == 'E', 1, 0)
df['Class_F'] = np.where(df['Class'] == 'F', 1, 0)
df

Class  Class_B  Class_C  Class_D  Class_E  Class_F
0     A        0        0        0        0        0
1     B        1        0        0        0        0
2     C        0        1        0        0        0
3     E        0        0        0        1        0
4     D        0        0        1        0        0
5     D        0        0        1        0        0
6     A        0        0        0        0        0
7     F        0        0        0        0        1

In [62]:
# loc과 boolean indexing
obj = {'Class' : ['A', 'B', 'C', 'E', 'D', 'D', 'A', 'F']}
df = pd.DataFrame(obj)
df

Class
0     A
1     B
2     C
3     E
4     D
5     D
6     A
7     F

In [63]:
df.loc[df['Class'] == 'B', 'Class_B'] = 1   # df의 Class 열이 B면 Class_B 열에 1 추가
df.loc[df['Class'] != 'B', 'Class_B'] = 0   # df의 Class 열이 B가 아니면 Class_B 열에 0 추가

df.loc[df['Class'] == 'C', 'Class_C'] = 1   # df의 Class 열이 C면 Class_C 열에 1 추가
df.loc[df['Class'] != 'C', 'Class_C'] = 0   # df의 Class 열이 C가 아니면 Class_C 열에 0 추가

df.loc[df['Class'] == 'D', 'Class_D'] = 1   # df의 Class 열이 D면 Class_D 열에 1 추가
df.loc[df['Class'] != 'D', 'Class_D'] = 0   # df의 Class 열이 D가 아니면 Class_D 열에 0 추가

df.loc[df['Class'] == 'E', 'Class_E'] = 1   # df의 Class 열이 E면 Class_E 열에 1 추가
df.loc[df['Class'] != 'E', 'Class_E'] = 0   # df의 Class 열이 E가 아니면 Class_E 열에 0 추가

df.loc[df['Class'] == 'F', 'Class_F'] = 1   # df의 Class 열이 F면 Class_F 열에 1 추가
df.loc[df['Class'] != 'F', 'Class_F'] = 0   # df의 Class 열이 F가 아니면 Class_F 열에 0 추가

In [64]:
df

Class  Class_B  Class_C  Class_D  Class_E  Class_F
0     A      0.0      0.0      0.0      0.0      0.0
1     B      1.0      0.0      0.0      0.0      0.0
2     C      0.0      1.0      0.0      0.0      0.0
3     E      0.0      0.0      0.0      1.0      0.0
4     D      0.0      0.0      1.0      0.0      0.0
5     D      0.0      0.0      1.0      0.0      0.0
6     A      0.0      0.0      0.0      0.0      0.0
7     F      0.0      0.0      0.0      0.0      1.0

#### 예제
Q. 학생의 id(s1, s2, s3, s4, s5, s6)를 담은 'student_id 컬럼과 시험점수(55, 90, 85, 71, 63, 99)를 담은 'score' 컬럼으로 구성된 데이터프레임을 생성하자. 그 후 시험점수가 90점 이상이면 '수, 80점 이상 90점 미만이면 '우, 70점 이상 80점 미만이면 '미, 60점 이상 70점 미만이면 '양, 60점 미만 이면 '가'로 분류하는 grade' 라는 컬럼을 새롭게 생성하고 생성한 grade 컬럼에 대하여 라벨 인코딩과 원-핫 인코딩을 시행해보자.

In [65]:
# 패키지/모듈/함수 호출
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [70]:
# df 생성
obj = {'student_id' : ['s1', 's2', 's3', 's4', 's5', 's6'],
       'score' : [55, 90, 85, 71, 63, 99]
      }
df = pd.DataFrame(obj)
df

student_id  score
0         s1     55
1         s2     90
2         s3     85
3         s4     71
4         s5     63
5         s6     99

In [75]:
# 구간화한 파생변수 [grade] 생성
df['grade'] = pd.cut(df['score'],
                     bins = [0, 60, 70, 80, 90, 100],               # bins을 내림차순으로 설정하면 'ValueError: bins must increase monotonically.' 오류가 남
                     labels = ['가', '양', '미', '우', '수'])
df

student_id  score grade
0         s1     55     가
1         s2     90     우
2         s3     85     우
3         s4     71     미
4         s5     63     양
5         s6     99     수

In [77]:
# sklearn을 활용한 라벨 인코딩
encoder = LabelEncoder()               # 라벨 인코더 객체 생성
encoder.fit(df.grade)                  # 적합
labels = encoder.transform(df.grade)   # 변환
labels

array([0, 4, 4, 1, 3, 2])

In [78]:
# 숫자값에 대응되는 원본 레이블
encoder.classes_

array(['가', '미', '수', '양', '우'], dtype=object)

In [80]:
# sklearn을 활용한 원-핫 인코딩
labels_2d = labels.reshape(-1, 1)  # 2d array
labels_2d

array([[0],
       [4],
       [4],
       [1],
       [3],
       [2]])

In [82]:
oh_encoder = OneHotEncoder(sparse_output=False)
oh_encoder.fit(labels_2d)

OneHotEncoder(sparse_output=False)

In [83]:
oh_labels = oh_encoder.transform(labels_2d)
oh_labels

array([[1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.]])

### 3절: 데이터 스케일링 (Data Scaling)
- 데이터들의 범위가 같아지도록 속성(변수)별로 값을 비례적으로 조정하는 과정
- **z-점수(z-score) 표준화**와 **min-max 정규화**가 많이 사용됨
- 변수들의 측정 단위나 값 범위가 다를 때 표준화/정규화를 적용하여 같은 기준으로 데이터를 파악할 수 있음

<br>

#### 표준화 (Standardizaiton)
- 각 개체들이 평균을 기준으로 얼마나 떨어져 있는지를 나타내는 값으로 변환하는 과정
- 표준화한 후 특정 범위를 벗어난 데이터를 확인하여 이상치 판별에 활용할 수 있음
- z-점수 표준화는 각 요소의 값에서 평균을 뺀 후 표준편차로 나누어 수행. (변환 후 데이터의 평균은 0, 표준편차는 1의 값을 갖게 됨)
- 파이썬에서 z-점수 표준화는 사이킷런 내의 preprocessing 모듈의 ```StandardScaler``` 클래스를 통해 수행 가능
- 클래스를 호출한 후 표준 스케일러 객체를 생성하여 ```fit()```과 ```transform()```을 사용하면 됨

In [91]:
# 패키지 불러오기
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler

In [93]:
# iris 데이터셋 호출
iris = load_iris()
data = pd.DataFrame(iris.data, columns=iris.feature_names)
data.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [94]:
# 표준 스케일러 객체 생성
std_scale = StandardScaler()

In [98]:
# 표준화 데이터로 변환
data_std = std_scale.fit_transform(data)
data_std = pd.DataFrame(data_std, columns = iris.feature_names)
data_std.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0          -0.900681          1.019004          -1.340227         -1.315444
1          -1.143017         -0.131979          -1.340227         -1.315444
2          -1.385353          0.328414          -1.397064         -1.315444
3          -1.506521          0.098217          -1.283389         -1.315444
4          -1.021849          1.249201          -1.340227         -1.315444

#### 정규화 (Normalization)
- 데이터의 범위를 0과 1 사이로 변환하여 데이터의 분포를 조정하는 방법
- 데이터군 내에서 특정 개체가 가지는 위치를 파악하고 비교할 때 사용
- 일반적으로 많이 사용되는 **min-max 정규화(최소최대 정규화)** 는 '$(x-min_x) / (max_x - min_x)$'의 공식을 이용하며 ```MinMaxScaler``` 클래스를 통해 수행 가능

<br>

참고) $(x-min_x) / (max_x - min_x)$ : (개체 - 해당 데이터의 최솟값) / (해당 데이터의 최댓값 - 해당 데이터의 최솟값)

In [99]:
from sklearn.preprocessing import MinMaxScaler

In [100]:
# iris 데이터셋 호출
iris = load_iris()
data = pd.DataFrame(iris.data, columns=iris.feature_names)
data.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [101]:
# minmax scaler 객체 생성
mm_scale = MinMaxScaler()

In [103]:
# 정규화 데이터로 변환
data_std = mm_scale.fit_transform(data)
data_std = pd.DataFrame(data_std, columns = iris.feature_names)
data_std.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0           0.222222          0.625000           0.067797          0.041667
1           0.166667          0.416667           0.067797          0.041667
2           0.111111          0.500000           0.050847          0.041667
3           0.083333          0.458333           0.084746          0.041667
4           0.194444          0.666667           0.067797          0.041667

### 4절: 데이터 축소
- 분석에 사용할 데이터의 변수가 너무 많을 때에는 주성분분석(PCA; Principal Component Analysis) 등을 사용하여 변수를 축소하고 데이터를 잘 설명할 수 있는 적절한 변수들만 선택하여 분석에 활용할 수 있음

<br>

#### 주성분분석
- 데이터에 여러 변수들이 있을 떄 서로 상관성이 높은 변수들의 선형결합으로 이루어진 **'주성분(Principal Component)'** 이라는 새로운 변수를 만들어 변수들을 요약하고 축소하는 기법
- 주성분은 여러 변수들의 선형 결합이므로, 각 변수에 내재되어 있는 중요한 정보의 손실이 있을 수도 있음 따라서 **주성분 기여율**을 사용하여 주성분이 데이터를 얼마나 잘 설명할 수 있는지를 평가함
- 주성분 기여율은 (주성분 변수의 분산) / (원 변수의 총 변동(각 변수들의 분산의 총합)) 으로, 총 변동에 대한 주성분의 설명력을 의미함
- 주성분의 분산이 전체 데이터의 흩어진 정도와 비슷하다면 해당 주성분은 적절하다고 판단될 수 있음
- 기여율은 1에 가까울수록 적절하고 0에 가까울수록 데이터에 대한 설명력이 떨어진다고 판단
- 첫 번째 주성분부터 차례대로 기여율을 합한 **누적 기여율(cumulative proportion)이 85% 이상**이 되면 해당 지점까지를 주성분의 수로 결정함

<br>

#### 파이썬을 이용한 주성분 분석
- 파이썬에서는 주성분 분성은 사이킷런 내 decomposition 모듈의 ```PCA``` 클래스를 통해 수행할 수 있음
- 클래스를 호출한 후 PCA 객체를 생성하여 ```fit()```과 ```transform()```을 통해 주성분 분석 가능

#### 예제
Q. 제공된 USArrests 데이터는 1973년 미국 50개주 100,000명의 인구 당 체포된 세 가지 강렬 범죄수(assault, murder, rape)와 각 주마다 도시에 거주하는 인구의 비율(%)로 구성되어있다. 주성분 분석을 수행하여 해당 데이터의 변수들을 가장 잘 요약하는 주성분을 구하고 해석해보자. 

In [104]:
# 패키지 불러오기
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

In [105]:
# USArrest 데이터 불러오기
# 주가 행 인덱스 레이블이 되도록 index_col = 0
df = pd.read_csv('data/예제/USArrests_rownames.csv', index_col = 0)
df.head()

Murder  Assault  UrbanPop  Rape
Alabama       13.2      236        58  21.2
Alaska        10.0      263        48  44.5
Arizona        8.1      294        80  31.0
Arkansas       8.8      190        50  19.5
California     9.0      276        91  40.6

In [106]:
# 주성분 분석 전에 표준화(스케일링)
# fit_transform은 한 번에 fit과 transform을 수행
x = StandardScaler().fit_transform(df)

In [108]:
# PCA 객체 생성
# 주성분의 수를 전체 컬럼 수로
pca = PCA(n_components = 4)
pca

PCA(n_components=4)

In [110]:
# 적합 후 변환 (배열)
pca_arr = pca.fit_transform(x)

In [111]:
# 주성분에 따른 분산 기여율과 누적 기여율
result = {'분산 기여율' : pca.explained_variance_ratio_,
          '누적 기여율' : pca.explained_variance_ratio_.cumsum()}
result

{'분산 기여율': array([0.62006039, 0.24744129, 0.0891408 , 0.04335752]),
 '누적 기여율': array([0.62006039, 0.86750168, 0.95664248, 1.        ])}

In [112]:
# 결과를 데이터프레임 형태로 변환, 전치하여 컬럼명이 주성분이 되도록 함
result = pd.DataFrame(result, index = ['PCA1', 'PCA2', 'PCA3', 'PCA4']).T
result

PCA1      PCA2      PCA3      PCA4
분산 기여율  0.62006  0.247441  0.089141  0.043358
누적 기여율  0.62006  0.867502  0.956642  1.000000

In [116]:
# 주성분 분석 결과 (85%를 넘는 누적 기여율은 PCA2)
pca = PCA(n_components=2)           # PCA 객체 생성
pca_arr = pca.fit_transform(x)      # 적합후 변환 (배열)
df_pca = pd.DataFrame(pca_arr, columns=['PCA1', 'PCA2'])   # 데이터프레임으로 변환
df_pca.head()

PCA1      PCA2
0  0.985566  1.133392
1  1.950138  1.073213
2  1.763164 -0.745957
3 -0.141420  1.119797
4  2.523980 -1.542934